FROM python:latest
WORKDIR /moviematch

RUN mkdir backend
COPY backend /moviematch/backend
RUN pip install -r backend/requirementsDocker.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn" , "-b", ":5000", "backend.api:app"]

