#Build step 1: build React-fe

FROM node as build-step
WORKDIR /app
ENV PATH /frontend/node_modules/.bin:$PATH
RUN mkdir data && mkdir frontend
COPY data /app/data
COPY frontend /app/frontend
RUN cd frontend && npm install && npm run build

#Build step 2: build nginx container
FROM nginx
COPY --from=build-step /app/frontend/build /usr/share/nginx/html
COPY nginx.default.conf /etc/nginx/conf.d/default.conf